Updated new details of SN2
opentensor/developer-docs pull request #195
Opened 2024-04-11 22:10 UTC by gagichce

Hi OTF!

Updated the details of SN2 to match it's new purpose.

Happy to make any changes!

2024-04-12 02:40 UTC, rajkaramchedu commented on docs/subnet-pages/subnet-2.md
> +The purpose of the Omron subnet is to provide verified AI inferences to optimize staking and re-staking yields.
Please add a new line here (just insert a blank line) so it breaks up the paragraph.

2024-04-12 02:46 UTC, rajkaramchedu commented on docs/subnet-pages/subnet-2.md
> +Specifically, this subnet enhances the Bittensor network as a whole by providing external uses for protocols outside the Bittensor ecosystem; thereby amplifying bittensor’s mission throughout a varie
Is this what you mean? See below. If correct, use this below wording:

"In specific, this subnet enhances the Bittensor network by providing utility to protocols and networks outside the Bittensor ecosystem. As a result, this subnet amplifies Bittensor’s mission throughout a variety of such external protocols and networks."

2024-04-12 02:48 UTC, rajkaramchedu commented on docs/subnet-pages/subnet-2.md
> +As well, this subnet provides internal uses for guiding bittensor users towards the most profitable validators to delegate to which benefits delegators and thereby the network as a whole.
Please use this wording below:

"Furthermore, this subnet provides internal benefits by guiding Bittensor users towards the most profitable validators to delegate to. This, in turn, benefits delegators and thereby benefits the Bittensor network as a whole."

2024-04-12 02:49 UTC, rajkaramchedu requested changes
Good work! See my comments. Thanks!

2024-04-16 20:41 UTC, rajkaramchedu commented
Redid these changes myself, so we can update the subnet page quickly. Closing this PR. See https://github.com/opentensor/developer-docs/pull/201

2024-04-16 20:42 UTC, merged

2024-04-18 09:44 UTC, gagichce commented
Thanks for merging this in!